repos:
  - repo: local
    hooks:
    - id: format
      name: Pint format
      entry: composer run lint:fix
      language: system
      types: [php]
    - id: lint
      name: PHPStan
      entry: composer run lint:stan
      language: system
      types: [php]
      exclude: ^tests/
    - id: test
      name: Pest test
      entry: composer run test:coverage
      language: system
      types: [php]
      pass_filenames: false
