repos:
  - repo: local
    hooks:
    - id: pint-format
      name: Pint format
      entry: composer run lint:fix
      language: system
      types: [php]
    - id: lint
      name: PHPStan + Pint
      entry: composer run lint
      language: system
      types: [php]
    - id: pest-test
      name: Pest test
      entry: composer run test
      language: system
      types: [php]
